#####Intro to Scripting: Final Project#####

### You will need to set your working directory to the location you have your data.
#I have my data copied in both my C drive (windows) and my subshell for linux
#To make it easier for working with desktop applications, I move data from my linux drive to my C drive
setwd("C:/FunGen/")


#### Install these packages
####DO NOT INSTALL THE SAME PACKAGE MULTIPLE TIMES
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install("DESeq2")
BiocManager::install("clusterProfiler")
BiocManager::install("AnnotationDbi")

## Load your packages 
library(DESeq2)
library(clusterProfiler)
library(AnnotationDbi)

###Read in count matrix data from mapper_hisat2.sh
###Manually load in your gene_count_matrix.csv with automatic headings and first column as row headers
countdata <- read.csv(file.choose(), row.names = "X")
dim(countdata)
head(countdata)

### Read in the PHENO_DATA.txt file
### This file has experimental design information that allows your samples to be pooled correctly
###This is not data generated by a script. This is data that would be provided by the researcher
coldata <-read.csv(file.choose(), row.names = "X")
dim(coldata)
head(coldata)

###Data transformation sanity check
#Check all sample IDs in colData are also in CountData and match their orders
all(rownames(coldata) %in% colnames(countdata))
countdata <- countdata[, rownames(coldata)]
all(rownames(coldata) == colnames(countdata))

#####DESeq2#####

###Create the DESEQ dataset using our two read-in data frames
###Ignore the warning messages. If the "dds" object is created, you should be fine
dds <- DESeqDataSetFromMatrix(countData = countdata, colData=coldata,  design = ~treatment)

###Filter out rows with fewer than 20 reads
dds <- dds[ rowSums(counts(dds)) > 19, ]
dds

###Create "factors" matching your control/treatment condition
###This allows DESeq to parse which data belong together
###To figure out what this should be for your own data, look at your "pheno_data" file and find the equivalent of "Treatment"
dds$condition <- factor(dds$treatment, levels=c("Ad_lib","Caloric_restriction"))

###Differential Expression Analysis
dds <- DESeq(dds)
res <- results(dds)
res

###Reorder results by p value
DGEresOrdered <- res[order(-res$pvalue),]
  DGEresOrdered

###Write your results to a file 
###This file can be used in the desktop version of GSEA
write.csv(as.data.frame(DGEresOrdered), file="DGESeq_results.csv")  

DGEinput = DGEresOrdered$pvalue
names(DGEinput) = rownames(DGEresOrdered)
DGEinput

#####GSEA#####
###We will use the "DGEinput" object as input for GSEA

genexp = gseKEGG(DGEinput, organism = "dpz", keyType = "kegg")
