#! /bin/bash

########## FunGen Course Instructions
## Purpose: The purpose of this script is to learn to make a scratch directory, define variables, and download data from NCBI SRA using the SRA run IDs
## Input Data: None
## Output Data: Downloaded read files, R1 and R2 files for each sample if paired-end data (FASTQ)
## More Information: SRA Toolkit https://www.ncbi.nlm.nih.gov/sra/docs/sradownload/
## Running the script on the Alabama Super Computer For more information: https://hpcdocs.asc.edu/content/slurm-queue-system
	## After you have this script in your home directory and you have made it exicutable using  "chmod +x [script name]", 
	## then run the script  by using "run_script [script name]"
	## suggested paramenters are below to submit this script.
		## queue: class
		## core: 1
		## time limit (HH:MM:SS): 04:00:00 
 		## Memory: 4gb
		## run on dmc
	## you can also put this command below in the this script. It reflects the parameters above, edit as needed.
#sbatch --qos=medium  -t 04:00:00 -N 1-1 -n 1 --mem-per-cpu=4000mb --constraint=dmc 


########## Load Modules (these are the software programs needed to run this script)
source /opt/asn/etc/asn-bash-profiles-special/modules.sh. ## This 
module load sra

##########  Define variables and make directories
## Edit Replace the numbers and the curly brackets with Your specific information
  ## make variable for your ASC ID so the directories are automatically made in YOUR directory
MyID={1}          	 ## Example: MyID=aubtss

## Make variable that represents YOUR working directory(WD) in scratch to hold your data. 
  ## Edit and replace the numbers and the curly brackets with Your specific information
DD={2}  		## Example: WD=/scratch/$MyID/PracticeRNAseq/RawData

##  make the directories in SCRATCH for holding the raw data
mkdir -p $DD
## move to the newly made directory
cd $DD

##########  Download the practice RNAseq data files from NCBI: SRA using the Run IDs
  ### from SRA use the SRA tool kit - see NCBI website https://www.ncbi.nlm.nih.gov/sra/docs/sradownload/
	## this downloads the SRA file and converts to fastq
	## -F 	Defline contains only original sequence name.
	## -I 	Append read id after spot id as 'accession.spot.readid' on defline.
	## splits the files into R1 and R2 (forward reads, reverse reads)

## These samples are from Bioproject PRJNA437447. An experiment on Daphnia pulex, 5 samples on ad lib feed, 5 samples on caloric restriction diet
## https://www.ncbi.nlm.nih.gov/bioproject?LinkName=sra_bioproject&from_uid=5206312

vdb-config --interactive

fastq-dump -F --split-files SRR6819014
fastq-dump -F --split-files SRR6819015
fastq-dump -F --split-files SRR6819016
fastq-dump -F --split-files SRR6819017
fastq-dump -F --split-files SRR6819018
fastq-dump -F --split-files SRR6819019
fastq-dump -F --split-files SRR6819020
fastq-dump -F --split-files SRR6819021
fastq-dump -F --split-files SRR6819022
fastq-dump -F --split-files SRR6819023

